backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "News & Events"
    folder: "src/content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Gallery"
    folder: "src/content/gallery"
    create: true
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Publications", "Special Events", "Books"],
        }
      - { label: "Caption", name: "caption", widget: "string", required: false }
